READY_PLAYER_ONE = "READY_PLAYER_ONE_RGB"
THE_GREAT_GATSBY = "THE_GREAT_GATSBY_RGB"
THE_LONG_DARK = "THE_LONG_DARK_RGB"

AUDIO_FILE = "InputAudio.wav"
VIDEO_FILE_MP4 = "InputVideo.mp4"
VIDEO_FILE_RGB = "InputVideo.rgb"
DATA_SET_LOCATION = "Data_Sets"